name: Bugs Report (English)
description: If you find something that goes wrong, please tell us!
labels: ["BUG"  ]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "Checklist"
    description: "Please check all these items before submit your issue"
    options:
    - label: "I confirmed this issue was still non be fixed on latest Parrot Channel Insider Preview release."
    - label: "I confirmed there are no similar issues currently opened on this repository."
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: The problem
    placeholder: "-（Answer here）-"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: Expected result
    placeholder: "-（Answer here）-"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: How can we reproduce this issue?
    placeholder: "-（Answer here）-"
  validations:
    required: true
- type: textarea
  id: "yml-5"
  attributes:
    label: Potential causes
    placeholder: "-（Answer here, optional）-"
- type: textarea
  id: "yml-6"
  attributes:
    label: Your System Environments 
    placeholder: "For Example：Windows 7 64-Bit SP1、Windows 10 Pro 64-Bit 1909、Windows 11 Pro 64-Bit 22H2"
  validations:
    required: true
- type: textarea
  id: "yml-7"
  attributes:
    label: BakaXL Version
    placeholder: "Plase go to “BakaXL Settings - About” and enter the Version and Internal Build ID
    
    For Example：BakaXL Public Sloth Channel 3.0.1.2 Build.2020.05.26.2135 / BakaXL Insider Preview 3.0.1.5 Parrot Channel Build.2020.5.30.2343"
  validations:
    required: true
- type: textarea
  id: "yml-8"
  attributes:
    label: Remarks
    placeholder: "-（Answer here, optional）-"
